# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      # - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
      - "ghcr.io/liatrio/vault-init:latest"
      - "ghcr.io/liatrio/vault-init:{{ .Tag }}"
      - "ghcr.io/liatrio/vault-init:v{{ .Major }}"
      - "ghcr.io/liatrio/vault-init:v{{ .Major }}.{{ .Minor }}"
    extra_files:
      - "go.mod"
      - "go.sum"
      - "main.go"
